spring:
  datasource:
    username: root
    password: wem161534807
    url: jdbc:mysql://8.136.81.197:3306/lime?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 20
      min-idle: 50
      max-active: 1000
  redis:
    database: 0
    host: 8.136.81.197
    port: 6379
    timeout: 30000ms
    password:
    lettuce:
      pool:
        max-active: 200
        max-idle: 8
        max-wait: -1
        min-idle: 0
  mvc:
     pathmatch:
       matching-strategy: ANT_PATH_MATCHER

server:
  port: 8866

jwt:
  secret: "daiyexiaojuzi"
  tokenPrefix: "Bearer "
  expireTime: 36000

bus-api:
  uname: "13105965306"
  secret: "d1f70195bf21669b6e6d6c3d8486d307"

ali-auth-code:
  access-key-id: "LTAI5tA1B9wPWyWrhAY8UDkX"
  access-key-secret: "eEH0yHrpc0qsTIsiPvXpzZTegcMKfI"

baidu-asr:
  grant_type: "client_credentials"
  client_id: "oGo7w0ncgfw9LBoai1LfEaYa"
  client_secret: "81NCVMdrZMnvCf6ZRbsr3ca4w8h3P2XA"